language: python
python:
  - 3.5
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
before_install:
  - sudo apt-get install -y -o Dpkg::Options::="--force-confnew" build-essential python3-dev libldap2-dev libsasl2-dev
  - .travis/docker-install.sh
  - cd src
install:
  - pip install coveralls
script:
#  - pylint synchromoodle
  - coverage run --source=synchromoodle setup.py test
after_success:
  - coveralls
notifications:
  slack: gfisemoy:Kf0RBB353oo4fEkpJXH9LEZ9