language: python
python:
  - 3.5
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
before_install: cd src
install:
  - pip install -e .[dev,test]
  - pip install coveralls
script:
#  - pylint synchromoodle
  - coverage run --source=synchromoodle setup.py test
after_success:
  - coveralls