database:
  database: moodle
  user: moodle
  password: moodle
  host: 192.168.1.100
  port: 9806
ldap:
  uri: ldap://192.168.1.100:9889
  username: cn=admin,ou=administrateurs,dc=esco-centre,dc=fr
  password: admin
  baseDN: dc=esco-centre,dc=fr
  structuresOU: ou=structures
  personnesOU: ou=people
  adminOU: ou=administrateurs
