version: '2.2'
services:
  moodle-db-test:
    image: 'bitnami/mariadb:10.1'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
    environment:
      - MARIADB_USER=moodle
      - MARIADB_DATABASE=moodle
      - MARIADB_PASSWORD=moodle
      - MARIADB_ROOT_PASSWORD=moodle
    ports:
      - ${DOCKER_DEVBOX_PORT_PREFIX}16:3306
    volumes:
      - "${COMPOSE_PROJECT_DIR}:/workdir" # Mount this volume to help loading/exporting dumps
      - 'moodle-db-test:/bitnami'
  ldap-test:
      build:
        context: .docker
        dockerfile: ldap/Dockerfile
      image: '${DOCKER_DEVBOX_REGISTRY}recia-env/ldap'
      init: true
      restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
      environment:
        - 'LDAP_BACKEND=bdb'
        - 'LDAP_DOMAIN=esco-centre.fr'
        - 'LDAP_BASE_DN=dc=esco-centre,dc=fr'
      ports:
        - ${DOCKER_DEVBOX_PORT_PREFIX}99:389
        - ${DOCKER_DEVBOX_PORT_PREFIX}46:636
      volumes:
        - 'ldap-data-test:/var/lib/ldap'
        - 'ldap-config-test:/etc/ldap/slapd.d'
volumes:
  moodle-db-test:
  ldap-data-test:
  ldap-config-test: