version: '2.2'
services:
  moodle-db-test:
    image: 'bitnami/mariadb:10.1'
    environment:
      - MARIADB_USER=moodle
      - MARIADB_DATABASE=moodle
      - MARIADB_PASSWORD=moodle
      - MARIADB_ROOT_PASSWORD=moodle
      - MARIADB_EXTRA_FLAGS=--sql-mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 3306
  ldap-test:
      build:
        context: .docker
        dockerfile: ldap/Dockerfile.pytest
      environment:
        - 'LDAP_BACKEND=bdb'
        - 'LDAP_DOMAIN=esco-centre.fr'
        - 'LDAP_BASE_DN=dc=esco-centre,dc=fr'
      ports:
        - 389
