version: '2.2'
networks:
  nginx-proxy:
    external: true
services:
  moodle:
    environment:
      - 'VIRTUAL_HOST=moodle.${DOCKER_DEVBOX_DOMAIN_PREFIX}.${DOCKER_DEVBOX_DOMAIN}'
    networks:
      - default
      - nginx-proxy
