version: '2.2'
networks:
  reverse-proxy:
    name: '${DOCKER_DEVBOX_REVERSE_PROXY_NETWORK}'
    external: true
services:
  moodle:
    environment:
      - 'VIRTUAL_HOST=moodle.${DOCKER_DEVBOX_DOMAIN_PREFIX}.${DOCKER_DEVBOX_DOMAIN}'
      - 'VIRTUAL_PORT=80'
    labels:
      - traefik.enable=true
      - 'traefik.frontend.rule=Host:moodle.${DOCKER_DEVBOX_DOMAIN_PREFIX}.${DOCKER_DEVBOX_DOMAIN}'
      - traefik.port=80
    networks:
      - default
      - reverse-proxy
  moodle-db-2:
    image: 'bitnami/mariadb:10.1'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
    environment:
      - MARIADB_USER=moodle
      - MARIADB_DATABASE=moodle
      - MARIADB_PASSWORD=moodle
      - MARIADB_ROOT_PASSWORD=moodle
      - MARIADB_EXTRA_FLAGS=--sql-mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - ${DOCKER_DEVBOX_PORT_PREFIX}07:3306
    volumes:
      - "${COMPOSE_PROJECT_DIR}:/workdir" # Mount this volume to help loading/exporting dumps
      - 'moodle-db-2:/bitnami'
volumes:
  moodle-db-2:
