version: '2.2'
networks:
  nginx-proxy:
    external: true
services:
  moodle:
    environment:
      - 'VIRTUAL_HOST=moodle.${DOCKER_DEVBOX_DOMAIN_PREFIX}.${DOCKER_DEVBOX_DOMAIN}'
    networks:
      - default
      - nginx-proxy
  moodle-db-2:
    image: 'bitnami/mariadb:10.1'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
    environment:
      - MARIADB_USER=moodle
      - MARIADB_DATABASE=moodle
      - MARIADB_PASSWORD=moodle
      - MARIADB_ROOT_PASSWORD=moodle
      - MARIADB_EXTRA_FLAGS=--character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - ${DOCKER_DEVBOX_PORT_PREFIX}07:3306
    volumes:
      - "${COMPOSE_PROJECT_DIR}:/workdir" # Mount this volume to help loading/exporting dumps
      - 'moodle-db-2:/bitnami'
volumes:
  moodle-db-2:
