logging:
  formatters:
    console:
      format: '[%(name)s] %(levelname)s [%(name)s.%(funcName)s:%(lineno)d] %(message)s'
    file:
      format: '[%(asctime)s] [%(name)s] %(levelname)s %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: console
      stream: ext://sys.stdout
    file:
      class: logging.handlers.TimedRotatingFileHandler
      formatter: file
      when: 'D'
      filename: 'logs/synchromoodle.log'
    file-error:
      class: logging.handlers.TimedRotatingFileHandler
      level: ERROR
      formatter: file
      when: 'D'
      filename: 'logs/synchromoodle.error.log'
  root:
    level: INFO
    handlers: [console, file, file-error]
actions:
- id: academique
  timestampStore:
    file: "trtAcademique_precedent.txt"
  etablissements:
    listeEtab: ["0290009C", "0291595B"]
