users:
  prefixAdminMoodleLocal: "(esco|clg37):admin:Moodle:local:"
  prefixAdminLocal: "(esco|clg37):admin:local:"
etablissements:
  fileTrtPrecedent: "test_precedent.txt"
  listeEtab: ["0290009C"]
  listeEtabSansMail: []