delete:
  ids_users_undeletable: [1, 2, 492066]
webservice:
  token: '06ff10543c4488601f6f5cc7f1884f3b'
  moodle_host: 'https://moodle.synchro-moodle.test'
logging:
  formatters:
    console:
      format: '[%(name)s] [%(levelname)s] %(message)s'
    file:
      format: '[%(asctime)s] [%(name)s] [%(levelname)s] %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: console
      stream: ext://sys.stdout
    file:
      class: logging.handlers.TimedRotatingFileHandler
      formatter: file
      when: midnight
      filename: 'logs/synchromoodle.log'
    file-error:
      class: logging.handlers.TimedRotatingFileHandler
      level: ERROR
      formatter: file
      when: midnight
      filename: 'logs/synchromoodle.error.log'
  root:
    level: INFO
    handlers: [console, file, file-error]
actions:
- id: academique
  timestampStore:
    file: "trtAcademique_precedent.txt"
  etablissements:
    liste_etab: ["0290009C", "0291595B"]
#- id: nettoyage
#  type: nettoyage
#  timestampStore:
#    file: "trtNettoyage_precedent.txt"
#  etablissements:
#    liste_etab: ["0290009C", "0291595B"]
